--liquibase formatted sql

--changeset alex:1

CREATE TABLE word
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    word text NOT NULL UNIQUE ,
    transcription text NOT NULL ,
    translation TEXT NOT NULL
);