--liquibase formatted sql

--changeset alex:1

CREATE TABLE users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email varchar(320) NOT NULL UNIQUE ,
    first_name varchar(127) NOT NULL ,
    last_name varchar(127) NOT NULL ,
    password text NOT NULL ,
    avatar text
)